In [1]:
import numpy as np

In [2]:
# defining a vector
v1 = np.array([1, -1, 2])
v2 = np.array([ 2, 5, 2])

print(v1 + v2)

[3 4 4]


In [3]:
print(v1 - v2)

[-1 -6  0]


In [4]:
# scalar Multiplication 

print(3 * v1)

[ 3 -3  6]


In [ ]:
print(np.linalg.norm(v1)) # This command calculates the vector length (magnitude) of a vector named v1

2.449489742783178


In [7]:
s = np.dot(v1, v2)
print(s)

1


In [ ]:
# Matrix Algebra

array1 = np.array([[1, 3], [4, 5]])
array2 = np.array([[1, 3], [4, 5]])
print(array1.size)
print(array2.size)

4
4


In [10]:
array3 = array1 - array2
print(array3.size)

4


In [13]:
m = np.array([[1,2, 3, 4, 5]])
print(m.shape)

(1, 5)


In [ ]:
n = np.array([[1], [2], [3], [4] ])
print(n.shape)

(4, 1)


In [20]:
k = m * n
print(k)

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]]
