In [3]:
import numpy as np


In [2]:
arr1 = np.array([[1, 7], [2, 1], [3, 2]])
print(arr1)

[[1 7]
 [2 1]
 [3 2]]


In [8]:
arr2 = np.array([[1, 1], [1, -1], [1, -2]])
print(arr2)

[[ 1  1]
 [ 1 -1]
 [ 1 -2]]


In [ ]:
array1 = np.add(arr1, arr2)
print(array1)

[[2 8]
 [3 0]
 [4 0]]


In [10]:
array2 = np.subtract(arr1, arr2)
print(array2)

[[0 6]
 [1 2]
 [2 4]]


In [11]:
array3 = np.multiply(arr1, arr2)
print(array3)

[[ 1  7]
 [ 2 -1]
 [ 3 -4]]


In [12]:
a = np.array([[1, 2, 3], [1, -2, 3]])
print(a)

[[ 1  2  3]
 [ 1 -2  3]]


In [13]:
c = np.dot(arr1, a)
print(c)

[[  8 -12  24]
 [  3   2   9]
 [  5   2  15]]


In [21]:
det = np.linalg.det(c)
print(det)
inverse = np.linalg.inv(c)
print(inverse)

0.0


LinAlgError: Singular matrix

In [25]:
m = np.array([[1, -1], [2, 3]])
n = np.linalg.inv(m)
print(n)

[[ 0.6  0.2]
 [-0.4  0.2]]


In [28]:
print(np.dot(m, n))

[[ 1.00000000e+00 -5.55111512e-17]
 [ 1.11022302e-16  1.00000000e+00]]


In [5]:
array = np.array([1, 2, 3])
print(type(array))

<class 'numpy.ndarray'>


In [6]:
print(array.ndim) # no of dimensions

1


In [7]:
num = np.zeros(3)
print(num)

[0. 0. 0.]


In [12]:
num = np.ones((3, 3))
print(num)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
a = np.full((2, 2), 9)
print(a)

[[9 9]
 [9 9]]


In [15]:
arr = np.arange(1, 10, 2)
print(arr)


[1 3 5 7 9]


In [20]:
i = np.identity(4)
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
