In [1]:
import numpy as np


In [3]:
array = np.array([1,2, 3,10, 23, 7, 18])

In [ ]:
# For sorting an array
print(np.sort(array))

[ 1  2  3  7 10 18 23]


In [5]:
print(np.argsort(array))

[0 1 2 5 3 6 4]


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6]


AttributeError: module 'numpy' has no attribute 'arrange'